In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
data=pd.read_csv('avocado_ripeness_dataset.csv')    #converting the csv file to dataframe
data    #display the data

,firmness,hue,saturation,brightness,color_category,sound_db,weight_g,size_cm3,ripeness
0,14.5,19,40,26,black,34,175,261,ripe
1,71.7,53,69,75,green,69,206,185,pre-conditioned
2,88.5,60,94,46,dark green,79,220,143,hard
3,93.8,105,87,41,dark green,75,299,140,hard
4,42.5,303,58,32,purple,63,200,227,breaking
...,...,...,...,...,...,...,...,...,...
245,94.1,83,80,58,dark green,72,254,134,hard
246,21.6,17,36,19,black,47,182,240,firm-ripe
247,14.0,4,40,17,black,37,188,274,ripe
248,61.5,63,87,75,green,65,261,162,pre-conditioned
249,17.8,27,30,36,black,40,190,272,ripe

In [ ]:
le=LabelEncoder()   #creating a label encoder

#converting the string feature as int for the machine to learn easier
data['color_category']=le.fit_transform(data['color_category'])

data    #displaying the modified dataset

,firmness,hue,saturation,brightness,color_category,sound_db,weight_g,size_cm3,ripeness
0,14.5,19,40,26,0,34,175,261,ripe
1,71.7,53,69,75,2,69,206,185,pre-conditioned
2,88.5,60,94,46,1,79,220,143,hard
3,93.8,105,87,41,1,75,299,140,hard
4,42.5,303,58,32,3,63,200,227,breaking
...,...,...,...,...,...,...,...,...,...
245,94.1,83,80,58,1,72,254,134,hard
246,21.6,17,36,19,0,47,182,240,firm-ripe
247,14.0,4,40,17,0,37,188,274,ripe
248,61.5,63,87,75,2,65,261,162,pre-conditioned
249,17.8,27,30,36,0,40,190,272,ripe

In [ ]:
#giving the X axis all the features except the feature to be predicted, i.e., 'ripeness'
X = data.drop('ripeness', axis=1)
#giving the y-axis the feature to be predicted, i.e., 'ripeness'
y = data['ripeness']
#splitting the data into training data and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=3)

In [ ]:
#creating a logistic regression model
#with max iterations scaled upto the total no: of cells in the dataframe
model = LogisticRegression(max_iter=2250)
#fitting the training data into the model
model.fit(X_train, y_train)

LogisticRegression(max_iter=2250)

In [ ]:
#storing the predicted output of the machine of X_test in y_pred
y_pred = model.predict(X_test)
#printing the accuracy score and classification report
#by comparing predicted values (y_pred) with actual values (y_test)
print("Accuracy of the ML model:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy of the ML model: 1.0

Classification Report:
                  precision    recall  f1-score   support

       breaking       1.00      1.00      1.00        16
      firm-ripe       1.00      1.00      1.00        14
           hard       1.00      1.00      1.00        20
pre-conditioned       1.00      1.00      1.00        14
           ripe       1.00      1.00      1.00        11

       accuracy                           1.00        75
      macro avg       1.00      1.00      1.00        75
   weighted avg       1.00      1.00      1.00        75